POST http://localhost:80/api/item
Content-Type: application/json

{}

###
POST http://localhost:8080/register
Content-Type: application/json

{
  "vorname": "Stefan",
  "nachname": "Testuser",
  "email": "stefan.testuser2@gmx.de",
  "anrede": "Herr",
  "titel": "Dr.",
  "istAdmin": "false",
  "passwort": "123"
}

